### ISSUE TITLE
dotenv pro review ze staging

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/k8s-base#18]

**Comment by ornsteinfilip** [comment]
Tzn do generatoru values-review.yaml default staging, mozno dale prepsat. @jindrichskupa navrhuje rozdeleni na DB env a zbytek.

```
ault:
  enabled: true
  authPath: auth/kubernetes-squared
  role: squared
  secrets:
    - name: dotenv
      path: k8s/apps/kv/squared/review/dotenv
      type: key-value
      
```
